version: '3'

services:
  nginx:
    image: nginx:1.16.0-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static
    ports:
      - "8081:8081"
